Update effector dependecies
effector/reflect pull request #23
Opened 2021-09-01 14:13 UTC by AlexandrHoroshih

Yesterday effector@22 was released. In this release effector's babel-plugin behaviour was changed and current version of `reflect` is not compatible with new effector version
Updated `effector` and `effector-react` to their latest versions at the moment

To work with effector@22 `reflect` must be built with updated babel-plugin

2021-09-01 14:13 UTC, AlexandrHoroshih commented
@sergeysova can you review?

2021-09-07 12:03 UTC, Imperyall commented
Did not forget bump package?

2021-09-10 14:04 UTC, sergeysova approved these changes

2021-09-20 09:00 UTC, sergeysova requested changes

2021-09-20 09:00 UTC, sergeysova commented on babel-preset.js
> +      ],
```suggestion
      [
        'effector/babel-plugin',
        {
          factories: ['@effector/reflect', '@effector/reflect/ssr'],
          noDefaults: true,
        },
        'effector-reflect',
      ],
```

2021-09-20 10:00 UTC, sergeysova approved these changes

2021-09-21 10:41 UTC, merged